// <auto-generated />
using System;
using FinanceSentry.Modules.BankSync.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FinanceSentry.Modules.BankSync.Migrations
{
    [DbContext(typeof(BankSyncDbContext))]
    partial class BankSyncDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("bank_sync")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FinanceSentry.Modules.BankSync.Domain.AuditLog", b =>
                {
                    b.Property<Guid>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<DateTime>("PerformedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ResourceId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("AuditId");

                    b.HasIndex("ResourceType", "ResourceId")
                        .HasDatabaseName("idx_audit_log_resource");

                    b.HasIndex("UserId", "PerformedAt")
                        .HasDatabaseName("idx_audit_log_user_performed_at");

                    b.ToTable("audit_logs", "bank_sync");
                });

            modelBuilder.Entity("FinanceSentry.Modules.BankSync.Domain.BankAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccountNumberLast4")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("CreditLimit")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasDefaultValue("EUR");

                    b.Property<decimal?>("CurrentBalance")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)");

                    b.Property<string>("ExternalAccountId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("LastSyncError")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastTransactionSyncAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("MonobankCredentialId")
                        .HasColumnType("uuid");

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ProductType")
                        .HasColumnType("text");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("SyncStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("pending");

                    b.Property<Guid?>("TrueLayerConnectionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExternalAccountId")
                        .IsUnique()
                        .HasDatabaseName("idx_bank_account_external_account_id_unique");

                    b.HasIndex("MonobankCredentialId");

                    b.HasIndex("SyncStatus")
                        .HasDatabaseName("idx_bank_account_sync_status");

                    b.HasIndex("TrueLayerConnectionId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_bank_account_user_id");

                    b.ToTable("BankAccounts", "bank_sync");
                });

            modelBuilder.Entity("FinanceSentry.Modules.BankSync.Domain.Category", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Key");

                    b.ToTable("categories", "bank_sync");
                });

            modelBuilder.Entity("FinanceSentry.Modules.BankSync.Domain.CommittedMerchantPin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("MerchantKey")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "MerchantKey")
                        .IsUnique()
                        .HasDatabaseName("idx_committed_merchant_pin_user_merchant_unique");

                    b.ToTable("committed_merchant_pins", "bank_sync");
                });

            modelBuilder.Entity("FinanceSentry.Modules.BankSync.Domain.Counterparty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FlowRole")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_counterparty_user_id");

                    b.ToTable("counterparties", "bank_sync");
                });

            modelBuilder.Entity("FinanceSentry.Modules.BankSync.Domain.CounterpartyRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CounterpartyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("MatchType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Pattern")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CounterpartyId")
                        .HasDatabaseName("idx_counterparty_rule_counterparty_id");

                    b.ToTable("counterparty_rules", "bank_sync");
                });

            modelBuilder.Entity("FinanceSentry.Modules.BankSync.Domain.MccCategory", b =>
                {
                    b.Property<int>("Mcc")
                        .HasColumnType("integer");

                    b.Property<string>("CategoryKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Mcc");

                    b.HasIndex("CategoryKey")
                        .HasDatabaseName("idx_mcc_category_category_key");

                    b.ToTable("mcc_categories", "bank_sync");
                });

            modelBuilder.Entity("FinanceSentry.Modules.BankSync.Domain.MerchantKeyword", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Keyword")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryKey")
                        .HasDatabaseName("idx_merchant_keyword_category_key");

                    b.HasIndex("Keyword")
                        .IsUnique()
                        .HasDatabaseName("idx_merchant_keyword_keyword_unique");

                    b.ToTable("merchant_keywords", "bank_sync");
                });

            modelBuilder.Entity("FinanceSentry.Modules.BankSync.Domain.MonobankCredential", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<byte[]>("AuthTag")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<byte[]>("EncryptedToken")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("Iv")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<int>("KeyVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<DateTime?>("LastSyncAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("idx_monobank_credential_user_unique");

                    b.ToTable("MonobankCredentials", "bank_sync");
                });

            modelBuilder.Entity("FinanceSentry.Modules.BankSync.Domain.SyncJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("LastTransactionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("pending");

                    b.Property<int>("TransactionCountDeduped")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("TransactionCountFetched")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("TransactionsSynced")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("idx_sync_job_account_id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("idx_sync_job_created_at");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_sync_job_status");

                    b.HasIndex("AccountId", "Status")
                        .HasDatabaseName("idx_sync_job_account_status");

                    b.ToTable("SyncJobs", "bank_sync");
                });

            modelBuilder.Entity("FinanceSentry.Modules.BankSync.Domain.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)");

                    b.Property<string>("ArchivedReason")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsPending")
                        .HasColumnType("boolean");

                    b.Property<int?>("Mcc")
                        .HasColumnType("integer");

                    b.Property<string>("MerchantCategory")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("MerchantName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("PostedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SourceCategory")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TransactionType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("UniqueHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("idx_transaction_account_id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("idx_transaction_created_at");

                    b.HasIndex("PostedDate")
                        .HasDatabaseName("idx_transaction_posted_date");

                    b.HasIndex("AccountId", "IsActive")
                        .HasDatabaseName("idx_transaction_account_active");

                    b.HasIndex("AccountId", "UniqueHash")
                        .IsUnique()
                        .HasDatabaseName("idx_transaction_account_unique_hash_unique");

                    b.ToTable("Transactions", "bank_sync");
                });

            modelBuilder.Entity("FinanceSentry.Modules.BankSync.Domain.TrueLayerConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<byte[]>("AuthTag")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTime?>("ConnectionExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<byte[]>("EncryptedRefreshToken")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("Iv")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<int>("KeyVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<DateTime?>("LastSyncAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProviderDisplayName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("CREATED");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Reference")
                        .IsUnique()
                        .HasDatabaseName("idx_truelayer_connection_reference_unique");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_truelayer_connection_user_id");

                    b.HasIndex("UserId", "ProviderId")
                        .IsUnique()
                        .HasDatabaseName("idx_truelayer_connection_user_provider_unique");

                    b.ToTable("TrueLayerConnections", "bank_sync");
                });

            modelBuilder.Entity("FinanceSentry.Modules.BankSync.Domain.BankAccount", b =>
                {
                    b.HasOne("FinanceSentry.Modules.BankSync.Domain.MonobankCredential", "MonobankCredential")
                        .WithMany("BankAccounts")
                        .HasForeignKey("MonobankCredentialId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FinanceSentry.Modules.BankSync.Domain.TrueLayerConnection", "TrueLayerConnection")
                        .WithMany("BankAccounts")
                        .HasForeignKey("TrueLayerConnectionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("MonobankCredential");

                    b.Navigation("TrueLayerConnection");
                });

            modelBuilder.Entity("FinanceSentry.Modules.BankSync.Domain.CounterpartyRule", b =>
                {
                    b.HasOne("FinanceSentry.Modules.BankSync.Domain.Counterparty", "Counterparty")
                        .WithMany("Rules")
                        .HasForeignKey("CounterpartyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Counterparty");
                });

            modelBuilder.Entity("FinanceSentry.Modules.BankSync.Domain.MccCategory", b =>
                {
                    b.HasOne("FinanceSentry.Modules.BankSync.Domain.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryKey")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FinanceSentry.Modules.BankSync.Domain.MerchantKeyword", b =>
                {
                    b.HasOne("FinanceSentry.Modules.BankSync.Domain.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryKey")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FinanceSentry.Modules.BankSync.Domain.SyncJob", b =>
                {
                    b.HasOne("FinanceSentry.Modules.BankSync.Domain.BankAccount", "Account")
                        .WithMany("SyncJobs")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("FinanceSentry.Modules.BankSync.Domain.Transaction", b =>
                {
                    b.HasOne("FinanceSentry.Modules.BankSync.Domain.BankAccount", "Account")
                        .WithMany("Transactions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("FinanceSentry.Modules.BankSync.Domain.BankAccount", b =>
                {
                    b.Navigation("SyncJobs");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("FinanceSentry.Modules.BankSync.Domain.Counterparty", b =>
                {
                    b.Navigation("Rules");
                });

            modelBuilder.Entity("FinanceSentry.Modules.BankSync.Domain.MonobankCredential", b =>
                {
                    b.Navigation("BankAccounts");
                });

            modelBuilder.Entity("FinanceSentry.Modules.BankSync.Domain.TrueLayerConnection", b =>
                {
                    b.Navigation("BankAccounts");
                });
#pragma warning restore 612, 618
        }
    }
}
