// <auto-generated />
using System;
using FinanceSentry.Modules.Wealth.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FinanceSentry.Modules.Wealth.Migrations
{
    [DbContext(typeof(WealthDbContext))]
    [Migration("20260928141916_M003_AddNetWorthSnapshotIsApproximate")]
    partial class M003_AddNetWorthSnapshotIsApproximate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FinanceSentry.Modules.Wealth.Domain.NetWorthSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal>("BankingTotal")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("BrokerageTotal")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("CryptoTotal")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<bool>("IsApproximate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_approximate");

                    b.Property<DateOnly>("SnapshotDate")
                        .HasColumnType("date");

                    b.Property<string>("StaleSleeves")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("stale_sleeves");

                    b.Property<DateTimeOffset>("TakenAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal>("TotalNetWorth")
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "SnapshotDate")
                        .IsUnique()
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_net_worth_snapshot_user_date_unique");

                    b.ToTable("net_worth_snapshots", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
