// <auto-generated />
using System;
using FinanceSentry.Modules.BrokerageSync.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FinanceSentry.Modules.BrokerageSync.Migrations
{
    [DbContext(typeof(BrokerageSyncDbContext))]
    [Migration("20260926131334_M009_AddBrokerageTradesAndCashTransactions")]
    partial class M009_AddBrokerageTradesAndCashTransactions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("brokerage_sync")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FinanceSentry.Modules.BrokerageSync.Domain.BrokerageCashTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(20, 4)
                        .HasColumnType("numeric(20,4)");

                    b.Property<string>("Code")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<long?>("Conid")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("FxRateToBase")
                        .HasPrecision(20, 8)
                        .HasColumnType("numeric(20,8)");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Isin")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Symbol")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("WithholdingTax")
                        .HasPrecision(20, 4)
                        .HasColumnType("numeric(20,4)");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Provider", "IdempotencyKey")
                        .IsUnique();

                    b.ToTable("BrokerageCashTransactions", "brokerage_sync");
                });

            modelBuilder.Entity("FinanceSentry.Modules.BrokerageSync.Domain.BrokerageHolding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AcquiredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("AverageCostUsd")
                        .HasPrecision(20, 8)
                        .HasColumnType("numeric(20,8)");

                    b.Property<decimal?>("CostBasisUsd")
                        .HasPrecision(20, 4)
                        .HasColumnType("numeric(20,4)");

                    b.Property<Guid?>("InstrumentId")
                        .HasColumnType("uuid");

                    b.Property<string>("InstrumentType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("ibkr");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(30, 10)
                        .HasColumnType("numeric(30,10)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("SyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("UsdValue")
                        .HasPrecision(20, 4)
                        .HasColumnType("numeric(20,4)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("InstrumentId");

                    b.HasIndex("UserId", "Symbol", "Provider")
                        .IsUnique();

                    b.ToTable("BrokerageHoldings", "brokerage_sync");
                });

            modelBuilder.Entity("FinanceSentry.Modules.BrokerageSync.Domain.BrokerageInstrument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Classification")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<long>("Conid")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InstrumentType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Isin")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Provider", "Conid")
                        .IsUnique();

                    b.ToTable("BrokerageInstruments", "brokerage_sync");
                });

            modelBuilder.Entity("FinanceSentry.Modules.BrokerageSync.Domain.BrokerageTrade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Commission")
                        .HasPrecision(20, 4)
                        .HasColumnType("numeric(20,4)");

                    b.Property<string>("CommissionCurrency")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<long?>("Conid")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("CostBasis")
                        .HasPrecision(20, 4)
                        .HasColumnType("numeric(20,4)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<decimal?>("FxRateToBase")
                        .HasPrecision(20, 8)
                        .HasColumnType("numeric(20,8)");

                    b.Property<string>("IbExecutionId")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("IbTradeId")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid?>("InstrumentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Isin")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.Property<string>("OpenCloseIndicator")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<DateTime?>("OpenDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Price")
                        .HasPrecision(20, 8)
                        .HasColumnType("numeric(20,8)");

                    b.Property<decimal>("Proceeds")
                        .HasPrecision(20, 4)
                        .HasColumnType("numeric(20,4)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(30, 10)
                        .HasColumnType("numeric(30,10)");

                    b.Property<decimal?>("RealizedPnl")
                        .HasPrecision(20, 4)
                        .HasColumnType("numeric(20,4)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal?>("Taxes")
                        .HasPrecision(20, 4)
                        .HasColumnType("numeric(20,4)");

                    b.Property<DateTime>("TradeDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("InstrumentId");

                    b.HasIndex("UserId", "Provider", "IbExecutionId")
                        .IsUnique();

                    b.ToTable("BrokerageTrades", "brokerage_sync");
                });

            modelBuilder.Entity("FinanceSentry.Modules.BrokerageSync.Domain.IBKRCredential", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<byte[]>("AccessTokenSecretAuthTag")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("AccessTokenSecretIv")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("AccountId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ConsumerKey")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DhParam")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("EncryptedAccessTokenSecret")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("EncryptedEncryptionKey")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("EncryptedSignatureKey")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("EncryptionKeyAuthTag")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("EncryptionKeyIv")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("KeyVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<DateTime?>("LastSyncAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastSyncError")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<byte[]>("SignatureKeyAuthTag")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("SignatureKeyIv")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("IBKRCredentials", "brokerage_sync");
                });

            modelBuilder.Entity("FinanceSentry.Modules.BrokerageSync.Domain.IBKRFlexCredential", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("EncryptedToken")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("KeyVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<string>("LastError")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("QueryId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<byte[]>("TokenAuthTag")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("TokenIv")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("IBKRFlexCredentials", "brokerage_sync");
                });

            modelBuilder.Entity("FinanceSentry.Modules.BrokerageSync.Domain.BrokerageHolding", b =>
                {
                    b.HasOne("FinanceSentry.Modules.BrokerageSync.Domain.BrokerageInstrument", null)
                        .WithMany()
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("FinanceSentry.Modules.BrokerageSync.Domain.BrokerageTrade", b =>
                {
                    b.HasOne("FinanceSentry.Modules.BrokerageSync.Domain.BrokerageInstrument", null)
                        .WithMany()
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.SetNull);
                });
#pragma warning restore 612, 618
        }
    }
}
