<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FinanceSentry.Core\FinanceSentry.Core.csproj" />
    <ProjectReference Include="..\FinanceSentry.Modules.Alerts\FinanceSentry.Modules.Alerts.csproj" />
    <ProjectReference Include="..\FinanceSentry.Modules.BrokerageSync\FinanceSentry.Modules.BrokerageSync.csproj" />
    <ProjectReference Include="..\FinanceSentry.Modules.Companion\FinanceSentry.Modules.Companion.csproj" />
    <ProjectReference Include="..\FinanceSentry.Modules.Events\FinanceSentry.Modules.Events.csproj" />
    <ProjectReference Include="..\FinanceSentry.Modules.Radar\FinanceSentry.Modules.Radar.csproj" />
    <ProjectReference Include="..\FinanceSentry.Modules.Research\FinanceSentry.Modules.Research.csproj" />
    <ProjectReference Include="..\FinanceSentry.Modules.Risk\FinanceSentry.Modules.Risk.csproj" />
    <ProjectReference Include="..\FinanceSentry.Modules.Wealth\FinanceSentry.Modules.Wealth.csproj" />
  </ItemGroup>

</Project>
