// <auto-generated />
using System;
using FinanceSentry.Modules.Research.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FinanceSentry.Modules.Research.Migrations
{
    [DbContext(typeof(ResearchDbContext))]
    [Migration("20260921161302_M015_NewsSourceRetirement")]
    partial class M015_NewsSourceRetirement
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("research")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FinanceSentry.Modules.Research.Domain.AnalystAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateOnly>("ActionDate")
                        .HasColumnType("date");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Firm")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTimeOffset>("IngestedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("NewRating")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<decimal?>("NewTarget")
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("PriorRating")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<decimal?>("PriorTarget")
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("SourceUrl")
                        .HasColumnType("text");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.HasKey("Id");

                    b.HasIndex("ActionDate")
                        .IsDescending()
                        .HasDatabaseName("idx_analyst_actions_date");

                    b.HasIndex("Ticker", "ActionDate")
                        .HasDatabaseName("idx_analyst_actions_ticker_date");

                    b.HasIndex("Ticker", "Firm", "ActionDate", "ActionType")
                        .IsUnique()
                        .HasDatabaseName("idx_analyst_actions_dedup");

                    b.ToTable("analyst_actions", "research");
                });

            modelBuilder.Entity("FinanceSentry.Modules.Research.Domain.AnalystUniverseMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("AddedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.HasKey("Id");

                    b.HasIndex("Ticker")
                        .IsUnique()
                        .HasDatabaseName("idx_analyst_universe_ticker");

                    b.ToTable("analyst_universe_members", "research");
                });

            modelBuilder.Entity("FinanceSentry.Modules.Research.Domain.AssetLedgerRead", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("GeneratedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Narrative")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourceFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Symbol")
                        .IsUnique()
                        .HasDatabaseName("idx_asset_ledger_reads_user_symbol");

                    b.ToTable("asset_ledger_reads", "research");
                });

            modelBuilder.Entity("FinanceSentry.Modules.Research.Domain.CandidateScore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("uuid");

                    b.Property<string>("CrowdingClass")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Evidence")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("FormulaVersion")
                        .HasColumnType("integer");

                    b.Property<int?>("FundamentalsScore")
                        .HasColumnType("integer");

                    b.Property<string>("IpsFit")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("ScoredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("StructureScore")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId", "ScoredAt")
                        .HasDatabaseName("idx_candidate_scores_candidate_scored");

                    b.ToTable("candidate_scores", "research");
                });

            modelBuilder.Entity("FinanceSentry.Modules.Research.Domain.InvestmentPolicyStatement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AllocationTargets")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("ContributionPlan")
                        .HasColumnType("jsonb");

                    b.Property<int>("CoolingOffDays")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<decimal?>("EmergencyCushionUsd")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Exclusions")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Goals")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("MaxDrawdownTolerancePct")
                        .HasColumnType("numeric(6,2)");

                    b.Property<int>("PrimaryHorizonYears")
                        .HasColumnType("integer");

                    b.Property<string>("RebalancingRule")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("ReviewCadence")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("RiskCapacity")
                        .HasColumnType("integer");

                    b.Property<int>("RiskTolerance")
                        .HasColumnType("integer");

                    b.Property<string>("SellDiscipline")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "IsCurrent")
                        .HasDatabaseName("idx_ips_user_current");

                    b.HasIndex("UserId", "Version")
                        .IsUnique()
                        .HasDatabaseName("idx_ips_user_version");

                    b.ToTable("investment_policy_statements", "research");
                });

            modelBuilder.Entity("FinanceSentry.Modules.Research.Domain.InvestmentThesis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset?>("BrokenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("BrokenReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Catalysts")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<decimal?>("EntryPrice")
                        .HasColumnType("numeric(18,6)");

                    b.Property<string>("InvalidationTriggers")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("KeyDataPoints")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("ThesisText")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Ticker")
                        .HasDatabaseName("idx_thesis_user_ticker");

                    b.ToTable("theses", "research");
                });

            modelBuilder.Entity("FinanceSentry.Modules.Research.Domain.MacroEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Event")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateOnly>("EventDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly?>("EventTime")
                        .HasColumnType("time without time zone");

                    b.Property<string>("Importance")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTimeOffset>("IngestedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("EventDate")
                        .HasDatabaseName("idx_macro_date");

                    b.HasIndex("EventDate", "Region", "Event")
                        .IsUnique()
                        .HasDatabaseName("idx_macro_dedup");

                    b.ToTable("macro_events", "research");
                });

            modelBuilder.Entity("FinanceSentry.Modules.Research.Domain.NewsArticle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Categories")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("IngestedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTimeOffset>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Summary")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("ThesisIds")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Tickers")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.HasIndex("ContentHash")
                        .IsUnique()
                        .HasDatabaseName("idx_news_hash");

                    b.HasIndex("PublishedAt")
                        .IsDescending()
                        .HasDatabaseName("idx_news_published");

                    b.ToTable("news_articles", "research");
                });

            modelBuilder.Entity("FinanceSentry.Modules.Research.Domain.NewsSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("ConsecutiveFailures")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Keywords")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("LastFailureReason")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastSuccessAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTimeOffset?>("RetiredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RetiredReason")
                        .HasColumnType("text");

                    b.Property<Guid?>("ThesisId")
                        .HasColumnType("uuid");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ThesisId")
                        .HasDatabaseName("idx_news_sources_thesis");

                    b.HasIndex("Url")
                        .IsUnique()
                        .HasDatabaseName("idx_news_sources_url");

                    b.ToTable("news_sources", "research");
                });

            modelBuilder.Entity("FinanceSentry.Modules.Research.Domain.OpportunityCandidate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NominationReasons")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("PromotedThesisId")
                        .HasColumnType("uuid");

                    b.Property<string>("RejectedReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Status")
                        .HasDatabaseName("idx_opportunity_candidates_user_status");

                    b.HasIndex("UserId", "Ticker")
                        .HasDatabaseName("idx_opportunity_candidates_user_ticker");

                    b.ToTable("opportunity_candidates", "research");
                });

            modelBuilder.Entity("FinanceSentry.Modules.Research.Domain.QuoteCacheEntry", b =>
                {
                    b.Property<string>("Ticker")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasDefaultValue("USD");

                    b.Property<DateTimeOffset>("FetchedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsStale")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("MarketState")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("unknown");

                    b.Property<decimal?>("PreviousClose")
                        .HasColumnType("numeric(18,6)");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric(18,6)");

                    b.Property<DateTimeOffset?>("RegularMarketTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ResolvedTicker")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Session")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("unknown");

                    b.Property<DateTimeOffset?>("SourcePriceTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Ticker");

                    b.ToTable("quote_cache", "research");
                });

            modelBuilder.Entity("FinanceSentry.Modules.Research.Domain.RecommendationTrend", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("Buy")
                        .HasColumnType("integer");

                    b.Property<int>("Hold")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("IngestedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateOnly>("Period")
                        .HasColumnType("date");

                    b.Property<int>("Sell")
                        .HasColumnType("integer");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<int>("StrongBuy")
                        .HasColumnType("integer");

                    b.Property<int>("StrongSell")
                        .HasColumnType("integer");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.HasKey("Id");

                    b.HasIndex("Ticker", "Period")
                        .IsUnique()
                        .HasDatabaseName("idx_recommendation_trends_ticker_period");

                    b.ToTable("recommendation_trends", "research");
                });

            modelBuilder.Entity("FinanceSentry.Modules.Research.Domain.ResearchChunk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<int?>("EndOffset")
                        .HasColumnType("integer");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer");

                    b.Property<int?>("StartOffset")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TokenEstimate")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId", "Ordinal", "ContentHash")
                        .IsUnique()
                        .HasDatabaseName("idx_research_chunks_doc_ordinal_hash");

                    b.ToTable("research_chunks", "research");
                });

            modelBuilder.Entity("FinanceSentry.Modules.Research.Domain.ResearchDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("CanonicalUrl")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CapturedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("IndexFailureReason")
                        .HasColumnType("text");

                    b.Property<string>("IndexStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTimeOffset?>("IndexedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("SourceName")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ThesisIds")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Tickers")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PublishedAt")
                        .IsDescending()
                        .HasDatabaseName("idx_research_documents_published");

                    b.HasIndex("IndexStatus", "CapturedAt")
                        .HasDatabaseName("idx_research_documents_status_captured");

                    b.HasIndex("SourceType", "SourceId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("idx_research_documents_source_identity");

                    b.ToTable("research_documents", "research");
                });

            modelBuilder.Entity("FinanceSentry.Modules.Research.Domain.ResearchEmbedding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ChunkId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("Dimensions")
                        .HasColumnType("integer");

                    b.Property<int>("EmbeddingVersion")
                        .HasColumnType("integer");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.PrimitiveCollection<float[]>("Vector")
                        .IsRequired()
                        .HasColumnType("real[]");

                    b.HasKey("Id");

                    b.HasIndex("ChunkId", "Provider", "Model", "EmbeddingVersion")
                        .IsUnique()
                        .HasDatabaseName("idx_research_embeddings_chunk_provider_model_version");

                    b.ToTable("research_embeddings", "research");
                });

            modelBuilder.Entity("FinanceSentry.Modules.Research.Domain.ThesisEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal?>("BenchmarkPrice")
                        .HasColumnType("numeric(18,6)");

                    b.Property<string>("BenchmarkTicker")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("SPY");

                    b.Property<string>("DecisionNote")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("PricesPending")
                        .HasColumnType("boolean");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("SubjectPrice")
                        .HasColumnType("numeric(18,6)");

                    b.Property<string>("SubjectType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "PricesPending")
                        .HasDatabaseName("idx_thesis_events_pending");

                    b.HasIndex("SubjectType", "SubjectId", "Timestamp")
                        .HasDatabaseName("idx_thesis_events_subject");

                    b.HasIndex("UserId", "EventType", "Timestamp")
                        .HasDatabaseName("idx_thesis_events_user_type_time");

                    b.ToTable("thesis_events", "research");
                });

            modelBuilder.Entity("FinanceSentry.Modules.Research.Domain.ValuationSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CapturedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<decimal?>("ConsensusTarget")
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal?>("DividendYield")
                        .HasColumnType("numeric(8,6)");

                    b.Property<decimal?>("EvToEbitda")
                        .HasColumnType("numeric(12,4)");

                    b.Property<decimal?>("ForwardPe")
                        .HasColumnType("numeric(12,4)");

                    b.Property<bool>("IsStale")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.Property<decimal?>("TrailingPe")
                        .HasColumnType("numeric(12,4)");

                    b.HasKey("Id");

                    b.HasIndex("Ticker", "CapturedAt")
                        .HasDatabaseName("idx_valuation_snapshots_ticker_captured");

                    b.ToTable("valuation_snapshots", "research");
                });

            modelBuilder.Entity("FinanceSentry.Modules.Research.Domain.WatchlistItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("AddedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Exchange")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Ticker")
                        .IsUnique()
                        .HasDatabaseName("idx_watchlist_user_ticker");

                    b.ToTable("watchlist_items", "research");
                });

            modelBuilder.Entity("FinanceSentry.Modules.Research.Domain.NewsSource", b =>
                {
                    b.HasOne("FinanceSentry.Modules.Research.Domain.InvestmentThesis", null)
                        .WithMany()
                        .HasForeignKey("ThesisId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("FinanceSentry.Modules.Research.Domain.ResearchChunk", b =>
                {
                    b.HasOne("FinanceSentry.Modules.Research.Domain.ResearchDocument", null)
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FinanceSentry.Modules.Research.Domain.ResearchEmbedding", b =>
                {
                    b.HasOne("FinanceSentry.Modules.Research.Domain.ResearchChunk", null)
                        .WithMany()
                        .HasForeignKey("ChunkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
