using System.Text;
using FinanceSentry.Modules.CryptoSync.Domain.Exceptions;
using Org.BouncyCastle.Crypto.Parameters;
using Org.BouncyCastle.Crypto.Signers;
using Org.BouncyCastle.Security;

namespace FinanceSentry.Modules.CryptoSync.Infrastructure.RevolutX;

/// <summary>A Revolut X API key with its parsed Ed25519 signing key.</summary>
public sealed record RevolutXCredentials(string ApiKey, Ed25519PrivateKeyParameters PrivateKey);

/// <summary>
/// Revolut X request signing. The signature is a base64 Ed25519 signature over
/// <c>timestamp + METHOD + path + query + body</c>, concatenated with no separators, where path
/// starts at <c>/api</c>, query has no leading <c>?</c>, and body is minified JSON (empty for GET).
/// See https://developer.revolut.com/docs/x-api/revolut-x-crypto-exchange-rest-api.
/// </summary>
public static class RevolutXSigner
{
    public const string ApiKeyHeader = "X-Revx-API-Key";
    public const string TimestampHeader = "X-Revx-Timestamp";
    public const string SignatureHeader = "X-Revx-Signature";

    private const string PemPrivateKeyLabel = "PRIVATE KEY";

    /// <summary>
    /// Parses the key pair the user pasted: the API key Revolut X issued and the PKCS#8 PEM Ed25519
    /// private key whose public half was registered with it. Throws a
    /// <see cref="RevolutXException"/> (422) naming what is wrong, never echoing the key.
    /// </summary>
    public static RevolutXCredentials ParseCredentials(string apiKey, string privateKeyPem)
    {
        if (string.IsNullOrWhiteSpace(apiKey))
        {
            throw new RevolutXException("A Revolut X API key is required.");
        }

        return new RevolutXCredentials(apiKey.Trim(), ParsePrivateKey(privateKeyPem));
    }

    public static Ed25519PrivateKeyParameters ParsePrivateKey(string privateKeyPem)
    {
        if (string.IsNullOrWhiteSpace(privateKeyPem))
        {
            throw new RevolutXException("A Revolut X private key is required.");
        }

        if (privateKeyPem.Contains("PUBLIC KEY", StringComparison.Ordinal))
        {
            throw new RevolutXException(
                "That is the public key. Paste the Ed25519 private key (-----BEGIN PRIVATE KEY-----) "
                + "whose public half you registered with Revolut X.");
        }

        if (!privateKeyPem.Contains($"-----BEGIN {PemPrivateKeyLabel}-----", StringComparison.Ordinal))
        {
            throw new RevolutXException(
                "The Revolut X private key must be an unencrypted PKCS#8 PEM "
                + "(-----BEGIN PRIVATE KEY-----), as generated by `openssl genpkey -algorithm ed25519`.");
        }

        // Rebuilt from the armour so a key pasted with its line breaks collapsed still parses.
        var body = privateKeyPem
            .Replace($"-----BEGIN {PemPrivateKeyLabel}-----", string.Empty, StringComparison.Ordinal)
            .Replace($"-----END {PemPrivateKeyLabel}-----", string.Empty, StringComparison.Ordinal);
        body = string.Concat(body.Where(c => !char.IsWhiteSpace(c)));

        try
        {
            var key = PrivateKeyFactory.CreateKey(Convert.FromBase64String(body));
            return key as Ed25519PrivateKeyParameters
                ?? throw new RevolutXException(
                    "The Revolut X private key is not an Ed25519 key. Revolut X only accepts Ed25519.");
        }
        catch (Exception ex) when (ex is not RevolutXException)
        {
            throw new RevolutXException("The Revolut X private key could not be read as a PEM Ed25519 key.");
        }
    }

    public static string BuildMessage(string timestamp, string method, string path, string query, string body) =>
        string.Concat(timestamp, method.ToUpperInvariant(), path, query, body);

    public static string Sign(Ed25519PrivateKeyParameters privateKey, string message)
    {
        var signer = new Ed25519Signer();
        signer.Init(forSigning: true, privateKey);
        var bytes = Encoding.UTF8.GetBytes(message);
        signer.BlockUpdate(bytes, 0, bytes.Length);
        return Convert.ToBase64String(signer.GenerateSignature());
    }
}
