namespace FinanceSentry.Modules.BrokerageSync.Domain;

/// <summary>
/// A user's IBKR Flex Web Service credential — a token + Activity Flex Query id,
/// generated by the human in Client Portal (Reporting -> Flex Queries -> Flex Web
/// Service Configuration). This is a second, separate broker credential from
/// <see cref="IBKRCredential"/> (OAuth 1.0a): it authorizes a different host and
/// product (historical statement pulls), not live positions, and does not touch
/// the OAuth connection or its consent.
///
/// The token is short-lived and can be IP-restricted on IBKR's side; it is the
/// only secret on this credential and is stored encrypted at rest (AES-256-GCM,
/// same path as every other broker credential). The query id is not a secret.
/// </summary>
public sealed class IBKRFlexCredential
{
    public Guid Id { get; private set; }
    public Guid UserId { get; private set; }
    public bool IsActive { get; private set; }
    public DateTime? LastUsedAt { get; private set; }
    public string? LastError { get; private set; }
    public DateTime CreatedAt { get; private set; }

    /// <summary>The Activity Flex Query id (identifier, not secret).</summary>
    public string QueryId { get; private set; } = string.Empty;

    public byte[] EncryptedToken { get; private set; } = [];
    public byte[] TokenIv { get; private set; } = [];
    public byte[] TokenAuthTag { get; private set; } = [];

    public int KeyVersion { get; private set; } = 1;

    private IBKRFlexCredential() { }

    public IBKRFlexCredential(
        Guid userId,
        string queryId,
        byte[] encryptedToken,
        byte[] tokenIv,
        byte[] tokenAuthTag,
        int keyVersion)
    {
        Id = Guid.NewGuid();
        UserId = userId;
        IsActive = true;
        CreatedAt = DateTime.UtcNow;
        QueryId = queryId;
        EncryptedToken = encryptedToken;
        TokenIv = tokenIv;
        TokenAuthTag = tokenAuthTag;
        KeyVersion = keyVersion;
    }

    /// <summary>Replaces the stored token/query id for a re-connect, reactivating a previously cleared credential.</summary>
    public void Replace(
        string queryId,
        byte[] encryptedToken,
        byte[] tokenIv,
        byte[] tokenAuthTag,
        int keyVersion)
    {
        IsActive = true;
        LastUsedAt = null;
        LastError = null;
        QueryId = queryId;
        EncryptedToken = encryptedToken;
        TokenIv = tokenIv;
        TokenAuthTag = tokenAuthTag;
        KeyVersion = keyVersion;
    }

    public void RecordUseSuccess()
    {
        LastUsedAt = DateTime.UtcNow;
        LastError = null;
    }

    public void RecordUseError(string error) => LastError = error;

    public void Deactivate() => IsActive = false;

    /// <summary>
    /// Replaces this row's ciphertext with the same plaintext re-encrypted under a newer key
    /// (mirrors <see cref="IBKRCredential.RotateEncryption"/>). Not a business update.
    /// </summary>
    public void RotateEncryption(byte[] encryptedToken, byte[] tokenIv, byte[] tokenAuthTag, int keyVersion)
    {
        EncryptedToken = encryptedToken;
        TokenIv = tokenIv;
        TokenAuthTag = tokenAuthTag;
        KeyVersion = keyVersion;
    }
}
